version: '3.8'

services:
    baiucas-frontend:
        build:
            context: ./ExtensaoBaiucas
            dockerfile: Dockerfile
        ports:
            - '4200:4200'
        depends_on:
            - baiucas-backend
        networks:
            - app-network

    baiucas-backend:
        build:
            context: ./ExtensaoBaiucasBackEnd
            dockerfile: Dockerfile
        ports:
            - '80:80'
        depends_on:
            - baiucas-db
        networks:
            - app-network

    baiucas-db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: extensao-baiucas
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
