services:
  baiucas-frontend:
    build:
      context: ./ExtensaoBaiucas
      target: build
    ports:
      - "4200:4200"
    depends_on:
      - baiucas-backend
    volumes:
      - ./ExtensaoBaiucas:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  baiucas-backend:
    build:
      context: ./ExtensaoBaiucasBackEnd
      dockerfile: /docker/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./ExtensaoBaiucasBackEnd/.env
    depends_on:
      - baiucas-db
    networks:
      - app-network
    volumes:
      - ./ExtensaoBaiucasBackEnd:/var/www/html
      - ./ExtensaoBaiucasBackEnd/storage:/var/www/html/storage
      - /var/www/html/vendor

  baiucas-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: extensao-baiucas
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
