services:
  baiucas-frontend:
    build:
      context: ./ExtensaoBaiucas
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - baiucas-backend
    volumes:
      - ./ExtensaoBaiucas:/app
      - /app/node_modules
    command: ["npm", "start", "--", "--host", "0.0.0.0"]

  baiucas-backend:
    build:
      context: ./ExtensaoBaiucasBackEnd
      dockerfile: /docker/Dockerfile
    ports:
      - '80:80'
    env_file:
      - ./ExtensaoBaiucasBackEnd/.env
    depends_on:
      - baiucas-db
    networks:
      - app-network
    volumes:
      - ./ExtensaoBaiucasBackEnd:/var/www/html
      - /var/www/html/vendor

  baiucas-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: extensao-baiucas
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
