services:
  baiucas-frontend:
    build:
      context: ./ExtensaoBaiucas
      target: build
    ports:
      - "4200:4200"
    depends_on:
      - baiucas-backend
    volumes:
      - ./ExtensaoBaiucas:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_BASE_URL=http://baiucas-backend

  baiucas-backend:
    build:
      context: ./ExtensaoBaiucasBackEnd
      dockerfile: /docker/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./ExtensaoBaiucasBackEnd/.env
    depends_on:
      baiucas-db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./ExtensaoBaiucasBackEnd:/var/www/html
      - ./ExtensaoBaiucasBackEnd/storage:/var/www/html/storage
      - /var/www/html/vendor

  baiucas-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: extensao-baiucas
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
